// // <auto-generated />
// using System;
// using AspnetCoreMvcFull.Models;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// #nullable disable

// namespace AspnetCoreMvcFull.Migrations
// {
//     [DbContext(typeof(BaseDbContext))]
//     [Migration("20240519062950_InitialCreate")]
//     partial class InitialCreate
//     {
//         /// <inheritdoc />
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "7.0.10")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.BoPhan", b =>
//                 {
//                     b.Property<int>("IdboPhan")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDBoPhan");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdboPhan"));

//                     b.Property<string>("TenBoPhan")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("IdboPhan")
//                         .HasName("PK__BoPhan__0E503FF5B251FB90");

//                     b.ToTable("BoPhan", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.ChiTietHopDong", b =>
//                 {
//                     b.Property<int>("MaChiTietHopDong")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHopDong"));

//                     b.Property<int?>("IdtrangThai")
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     b.Property<int?>("MaHopDong")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaLoHang")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaPhuongTien")
//                         .HasColumnType("int");

//                     b.HasKey("MaChiTietHopDong")
//                         .HasName("PK__ChiTietH__0DA24B73CD4ACACF");

//                     b.HasIndex("IdtrangThai");

//                     b.HasIndex("MaHopDong");

//                     b.HasIndex("MaLoHang");

//                     b.HasIndex("MaPhuongTien");

//                     b.ToTable("ChiTietHopDong", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.ChiTietKho", b =>
//                 {
//                     b.Property<int>("MaChiTietKho")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietKho"));

//                     b.Property<int?>("MaKho")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaTraiCay")
//                         .HasColumnType("int");

//                     b.Property<int?>("SoLuong")
//                         .HasColumnType("int");

//                     b.HasKey("MaChiTietKho")
//                         .HasName("PK__ChiTietK__CE8258691EEA90BB");

//                     b.HasIndex("MaKho");

//                     b.HasIndex("MaTraiCay");

//                     b.ToTable("ChiTietKho", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.DoanhNghiep", b =>
//                 {
//                     b.Property<int>("MaDoanhNghiep")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoanhNghiep"));

//                     b.Property<string>("DiaChi")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int?>("MaQuocGia")
//                         .HasColumnType("int");

//                     b.Property<string>("Sdt")
//                         .HasMaxLength(20)
//                         .HasColumnType("nvarchar(20)")
//                         .HasColumnName("SDT");

//                     b.Property<string>("TenDoanhNghiep")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaDoanhNghiep")
//                         .HasName("PK__DoanhNgh__4D184EF6AE6A84B7");

//                     b.HasIndex("MaQuocGia");

//                     b.ToTable("DoanhNghiep", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.DoanhNghiepPhuongTien", b =>
//                 {
//                     b.Property<int>("IddoanhNghiepPhuongTien")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDDoanhNghiep_PhuongTien");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddoanhNghiepPhuongTien"));

//                     b.Property<int?>("IdtrangThai")
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     b.Property<int?>("MaDoanhNghiep")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaPhuongTien")
//                         .HasColumnType("int");

//                     b.HasKey("IddoanhNghiepPhuongTien");

//                     b.HasIndex("IdtrangThai");

//                     b.HasIndex("MaDoanhNghiep");

//                     b.HasIndex("MaPhuongTien");

//                     b.ToTable("DoanhNghiep_PhuongTien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.GiaTraiCay", b =>
//                 {
//                     b.Property<int>("MaGia")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGia"));

//                     b.Property<double?>("GiaTien")
//                         .HasColumnType("float");

//                     b.Property<int?>("MaTraiCay")
//                         .HasColumnType("int");

//                     b.Property<DateTime?>("NgayCapNhat")
//                         .HasColumnType("datetime");

//                     b.Property<int?>("SoLuong")
//                         .HasColumnType("int");

//                     b.HasKey("MaGia")
//                         .HasName("PK__tbGiaTra__3CD3DE5E63B5CA82");

//                     b.HasIndex("MaTraiCay");

//                     b.ToTable("GiaTraiCay", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.HopDong", b =>
//                 {
//                     b.Property<int>("MaHopDong")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

//                     b.Property<int?>("IdloaiHopDong")
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiHopDong");

//                     b.Property<int?>("IdtrangThai")
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     b.Property<int?>("MaDoiTac")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaNhanVien")
//                         .HasColumnType("int");

//                     b.Property<DateTime?>("NgayKy")
//                         .HasColumnType("datetime");

//                     b.Property<string>("TenHopDong")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.Property<double?>("TongGia")
//                         .HasColumnType("float");

//                     b.HasKey("MaHopDong")
//                         .HasName("PK__HopDong__36DD434222A7A746");

//                     b.HasIndex("IdloaiHopDong");

//                     b.HasIndex("IdtrangThai");

//                     b.HasIndex("MaDoiTac");

//                     b.HasIndex("MaNhanVien");

//                     b.ToTable("HopDong", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.Kho", b =>
//                 {
//                     b.Property<int>("MaKho")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

//                     b.Property<string>("DiaChi")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("TenKho")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaKho")
//                         .HasName("PK__Kho__3BDA93503DC9AB2D");

//                     b.ToTable("Kho", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.KhoPhuongTien", b =>
//                 {
//                     b.Property<int>("IdkhoPhuongTien")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDKho_PhuongTien");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdkhoPhuongTien"));

//                     b.Property<int?>("IdtrangThai")
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     b.Property<int?>("MaKho")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaPhuongTien")
//                         .HasColumnType("int");

//                     b.HasKey("IdkhoPhuongTien");

//                     b.HasIndex("IdtrangThai");

//                     b.HasIndex("MaKho");

//                     b.HasIndex("MaPhuongTien");

//                     b.ToTable("Kho_PhuongTien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoHang", b =>
//                 {
//                     b.Property<int>("MaLoHang")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoHang"));

//                     b.Property<double?>("DonGia")
//                         .HasColumnType("float");

//                     b.Property<int?>("IdloaiLoHang")
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiLoHang");

//                     b.Property<int?>("MaKho")
//                         .HasColumnType("int");

//                     b.Property<int?>("MaTraiCay")
//                         .HasColumnType("int");

//                     b.Property<int?>("SoLuong")
//                         .HasColumnType("int");

//                     b.HasKey("MaLoHang")
//                         .HasName("PK__tbLoHang__E81C10B22CE99985");

//                     b.HasIndex("IdloaiLoHang");

//                     b.HasIndex("MaKho");

//                     b.HasIndex("MaTraiCay");

//                     b.ToTable("LoHang", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiHopDong", b =>
//                 {
//                     b.Property<int>("IdloaiHopDong")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiHopDong");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdloaiHopDong"));

//                     b.Property<string>("LoaiHopDong1")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)")
//                         .HasColumnName("LoaiHopDong");

//                     b.HasKey("IdloaiHopDong")
//                         .HasName("PK__LoaiHopD__6C2A0CFF78795BF3");

//                     b.ToTable("LoaiHopDong", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiLoHang", b =>
//                 {
//                     b.Property<int>("IdloaiLoHang")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiLoHang");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdloaiLoHang"));

//                     b.Property<string>("LoaiLoHang1")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)")
//                         .HasColumnName("LoaiLoHang");

//                     b.HasKey("IdloaiLoHang")
//                         .HasName("PK__LoaiLoHa__FF67698FC02BA55C");

//                     b.ToTable("LoaiLoHang", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiPhuongTien", b =>
//                 {
//                     b.Property<int>("IdloaiPhuongTien")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiPhuongTien");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdloaiPhuongTien"));

//                     b.Property<string>("LoaiPhuongTien1")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)")
//                         .HasColumnName("LoaiPhuongTien");

//                     b.HasKey("IdloaiPhuongTien")
//                         .HasName("PK__LoaiPhuo__DE3BD94816B8F0CB");

//                     b.ToTable("LoaiPhuongTien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiTraiCay", b =>
//                 {
//                     b.Property<int>("IdloaiTraiCay")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiTraiCay");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdloaiTraiCay"));

//                     b.Property<string>("LoaiTraiCay1")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)")
//                         .HasColumnName("LoaiTraiCay");

//                     b.HasKey("IdloaiTraiCay")
//                         .HasName("PK_tbLoaiTraiCay");

//                     b.ToTable("LoaiTraiCay", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.NhaCungCap", b =>
//                 {
//                     b.Property<int>("MaNhaCungCap")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

//                     b.Property<string>("DiaChi")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<int?>("MaTraiCay")
//                         .HasColumnType("int");

//                     b.Property<string>("Sđt")
//                         .HasMaxLength(20)
//                         .HasColumnType("nvarchar(20)")
//                         .HasColumnName("SĐT");

//                     b.Property<string>("TenNhaCungCap")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaNhaCungCap")
//                         .HasName("PK__tbNhaCun__53DA9205F1817270");

//                     b.HasIndex("MaTraiCay");

//                     b.ToTable("NhaCungCap", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.NhanVien", b =>
//                 {
//                     b.Property<int>("MaNhanVien")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

//                     b.Property<string>("ChucVu")
//                         .HasMaxLength(20)
//                         .HasColumnType("nvarchar(20)");

//                     b.Property<int?>("IdboPhan")
//                         .HasColumnType("int")
//                         .HasColumnName("IDBoPhan");

//                     b.Property<int?>("IdtrangThai")
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     b.Property<string>("TenNhanVien")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaNhanVien")
//                         .HasName("PK__NhanVien__77B2CA47FC631E71");

//                     b.HasIndex("IdboPhan");

//                     b.HasIndex("IdtrangThai");

//                     b.ToTable("NhanVien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.PhuongTien", b =>
//                 {
//                     b.Property<int>("MaPhuongTien")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

//                     b.Property<int?>("IdloaiPhuongTien")
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiPhuongTien");

//                     b.Property<int?>("IdtrangThai")
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     b.Property<string>("TenPhuongTien")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaPhuongTien")
//                         .HasName("PK__PhuongTi__35B6C8B05D44C42F");

//                     b.HasIndex("IdloaiPhuongTien");

//                     b.HasIndex("IdtrangThai");

//                     b.ToTable("PhuongTien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.QuocGium", b =>
//                 {
//                     b.Property<int>("MaQuocGia")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuocGia"));

//                     b.Property<string>("TenQuocGia")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaQuocGia")
//                         .HasName("PK__QuocGia__30D69ACB5D4E9DF4");

//                     b.ToTable("QuocGia");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TraiCay", b =>
//                 {
//                     b.Property<int>("MaTraiCay")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTraiCay"));

//                     b.Property<int?>("IdloaiTraiCay")
//                         .HasColumnType("int")
//                         .HasColumnName("IDLoaiTraiCay");

//                     b.Property<string>("MoTa")
//                         .HasColumnType("nvarchar(max)");

//                     b.Property<string>("TenTraiCay")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("MaTraiCay")
//                         .HasName("PK_tbTraiCay");

//                     b.HasIndex("IdloaiTraiCay");

//                     b.ToTable("TraiCay", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiHopDong", b =>
//                 {
//                     b.Property<int>("IdtrangThai")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtrangThai"));

//                     b.Property<string>("TrangThai")
//                         .HasMaxLength(20)
//                         .HasColumnType("nvarchar(20)");

//                     b.HasKey("IdtrangThai")
//                         .HasName("PK__TrangTha__556586008AD2E149");

//                     b.ToTable("TrangThaiHopDong", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiNhanVien", b =>
//                 {
//                     b.Property<int>("IdtrangThai")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtrangThai"));

//                     b.Property<string>("TrangThai")
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("IdtrangThai");

//                     b.ToTable("TrangThaiNhanVien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiPhuongTien", b =>
//                 {
//                     b.Property<int>("IdtrangThai")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtrangThai"));

//                     b.Property<string>("TrangThai")
//                         .HasMaxLength(20)
//                         .HasColumnType("nvarchar(20)");

//                     b.HasKey("IdtrangThai")
//                         .HasName("PK__TrangTha__55658600F9E73C5A");

//                     b.ToTable("TrangThaiPhuongTien", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiVanChuyen", b =>
//                 {
//                     b.Property<int>("IdtrangThai")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int")
//                         .HasColumnName("IDTrangThai");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtrangThai"));

//                     b.Property<string>("TrangThai")
//                         .HasMaxLength(50)
//                         .HasColumnType("nchar(50)")
//                         .IsFixedLength();

//                     b.HasKey("IdtrangThai");

//                     b.ToTable("TrangThaiVanChuyen", (string)null);
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.ChiTietHopDong", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.TrangThaiHopDong", "IdtrangThaiNavigation")
//                         .WithMany("ChiTietHopDongs")
//                         .HasForeignKey("IdtrangThai")
//                         .HasConstraintName("FK_ChiTietHopDong_TrangThaiHopDong");

//                     b.HasOne("AspnetCoreMvcFull.Models.HopDong", "MaHopDongNavigation")
//                         .WithMany("ChiTietHopDongs")
//                         .HasForeignKey("MaHopDong")
//                         .HasConstraintName("FK_ChiTietHopDong_HopDong");

//                     b.HasOne("AspnetCoreMvcFull.Models.LoHang", "MaLoHangNavigation")
//                         .WithMany("ChiTietHopDongs")
//                         .HasForeignKey("MaLoHang")
//                         .HasConstraintName("FK_ChiTietHopDong_LoHang");

//                     b.HasOne("AspnetCoreMvcFull.Models.PhuongTien", "MaPhuongTienNavigation")
//                         .WithMany("ChiTietHopDongs")
//                         .HasForeignKey("MaPhuongTien")
//                         .HasConstraintName("FK_ChiTietHopDong_PhuongTien");

//                     b.Navigation("IdtrangThaiNavigation");

//                     b.Navigation("MaHopDongNavigation");

//                     b.Navigation("MaLoHangNavigation");

//                     b.Navigation("MaPhuongTienNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.ChiTietKho", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.Kho", "MaKhoNavigation")
//                         .WithMany("ChiTietKhos")
//                         .HasForeignKey("MaKho")
//                         .HasConstraintName("FK_ChiTietKho_Kho");

//                     b.HasOne("AspnetCoreMvcFull.Models.TraiCay", "MaTraiCayNavigation")
//                         .WithMany("ChiTietKhos")
//                         .HasForeignKey("MaTraiCay")
//                         .HasConstraintName("FK_ChiTietKho_TraiCay");

//                     b.Navigation("MaKhoNavigation");

//                     b.Navigation("MaTraiCayNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.DoanhNghiep", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.QuocGium", "MaQuocGiaNavigation")
//                         .WithMany("DoanhNghieps")
//                         .HasForeignKey("MaQuocGia")
//                         .HasConstraintName("FK_DoanhNghiep_QuocGia");

//                     b.Navigation("MaQuocGiaNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.DoanhNghiepPhuongTien", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.TrangThaiVanChuyen", "IdtrangThaiNavigation")
//                         .WithMany("DoanhNghiepPhuongTiens")
//                         .HasForeignKey("IdtrangThai")
//                         .HasConstraintName("FK_DoanhNghiep_PhuongTien_TrangThaiVanChuyen");

//                     b.HasOne("AspnetCoreMvcFull.Models.DoanhNghiep", "MaDoanhNghiepNavigation")
//                         .WithMany("DoanhNghiepPhuongTiens")
//                         .HasForeignKey("MaDoanhNghiep")
//                         .HasConstraintName("FK_DoanhNghiep_PhuongTien_DoanhNghiep");

//                     b.HasOne("AspnetCoreMvcFull.Models.PhuongTien", "MaPhuongTienNavigation")
//                         .WithMany("DoanhNghiepPhuongTiens")
//                         .HasForeignKey("MaPhuongTien")
//                         .HasConstraintName("FK_DoanhNghiep_PhuongTien_PhuongTien");

//                     b.Navigation("IdtrangThaiNavigation");

//                     b.Navigation("MaDoanhNghiepNavigation");

//                     b.Navigation("MaPhuongTienNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.GiaTraiCay", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.TraiCay", "MaTraiCayNavigation")
//                         .WithMany("GiaTraiCays")
//                         .HasForeignKey("MaTraiCay")
//                         .HasConstraintName("FK_GiaTraiCay_TraiCay");

//                     b.Navigation("MaTraiCayNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.HopDong", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.LoaiHopDong", "IdloaiHopDongNavigation")
//                         .WithMany("HopDongs")
//                         .HasForeignKey("IdloaiHopDong")
//                         .HasConstraintName("FK_HopDong_LoaiHopDong");

//                     b.HasOne("AspnetCoreMvcFull.Models.TrangThaiHopDong", "IdtrangThaiNavigation")
//                         .WithMany("HopDongs")
//                         .HasForeignKey("IdtrangThai")
//                         .HasConstraintName("FK_HopDong_TrangThaiHopDong");

//                     b.HasOne("AspnetCoreMvcFull.Models.DoanhNghiep", "MaDoiTacNavigation")
//                         .WithMany("HopDongs")
//                         .HasForeignKey("MaDoiTac")
//                         .HasConstraintName("FK_HopDong_DoanhNghiep");

//                     b.HasOne("AspnetCoreMvcFull.Models.NhaCungCap", "MaDoiTac1")
//                         .WithMany("HopDongs")
//                         .HasForeignKey("MaDoiTac")
//                         .HasConstraintName("FK_HopDong_NhaCungCap");

//                     b.HasOne("AspnetCoreMvcFull.Models.NhanVien", "MaNhanVienNavigation")
//                         .WithMany("HopDongs")
//                         .HasForeignKey("MaNhanVien")
//                         .HasConstraintName("FK_HopDong_NhanVien");

//                     b.Navigation("IdloaiHopDongNavigation");

//                     b.Navigation("IdtrangThaiNavigation");

//                     b.Navigation("MaDoiTac1");

//                     b.Navigation("MaDoiTacNavigation");

//                     b.Navigation("MaNhanVienNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.KhoPhuongTien", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.TrangThaiVanChuyen", "IdtrangThaiNavigation")
//                         .WithMany("KhoPhuongTiens")
//                         .HasForeignKey("IdtrangThai")
//                         .HasConstraintName("FK_Kho_PhuongTien_TrangThaiVanChuyen");

//                     b.HasOne("AspnetCoreMvcFull.Models.Kho", "MaKhoNavigation")
//                         .WithMany("KhoPhuongTiens")
//                         .HasForeignKey("MaKho")
//                         .HasConstraintName("FK_Kho_PhuongTien_Kho");

//                     b.HasOne("AspnetCoreMvcFull.Models.PhuongTien", "MaPhuongTienNavigation")
//                         .WithMany("KhoPhuongTiens")
//                         .HasForeignKey("MaPhuongTien")
//                         .HasConstraintName("FK_Kho_PhuongTien_PhuongTien");

//                     b.Navigation("IdtrangThaiNavigation");

//                     b.Navigation("MaKhoNavigation");

//                     b.Navigation("MaPhuongTienNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoHang", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.LoaiLoHang", "IdloaiLoHangNavigation")
//                         .WithMany("LoHangs")
//                         .HasForeignKey("IdloaiLoHang")
//                         .HasConstraintName("FK_LoHang_LoaiLoHang");

//                     b.HasOne("AspnetCoreMvcFull.Models.Kho", "MaKhoNavigation")
//                         .WithMany("LoHangs")
//                         .HasForeignKey("MaKho")
//                         .HasConstraintName("FK_LoHang_Kho");

//                     b.HasOne("AspnetCoreMvcFull.Models.TraiCay", "MaTraiCayNavigation")
//                         .WithMany("LoHangs")
//                         .HasForeignKey("MaTraiCay")
//                         .HasConstraintName("FK_LoHang_TraiCay");

//                     b.Navigation("IdloaiLoHangNavigation");

//                     b.Navigation("MaKhoNavigation");

//                     b.Navigation("MaTraiCayNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.NhaCungCap", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.TraiCay", "MaTraiCayNavigation")
//                         .WithMany("NhaCungCaps")
//                         .HasForeignKey("MaTraiCay")
//                         .HasConstraintName("FK_NhaCungCap_TraiCay");

//                     b.Navigation("MaTraiCayNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.NhanVien", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.BoPhan", "IdboPhanNavigation")
//                         .WithMany("NhanViens")
//                         .HasForeignKey("IdboPhan")
//                         .HasConstraintName("FK_NhanVien_BoPhan");

//                     b.HasOne("AspnetCoreMvcFull.Models.TrangThaiNhanVien", "IdtrangThaiNavigation")
//                         .WithMany("NhanViens")
//                         .HasForeignKey("IdtrangThai")
//                         .HasConstraintName("FK_NhanVien_TrangThaiNhanVien");

//                     b.Navigation("IdboPhanNavigation");

//                     b.Navigation("IdtrangThaiNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.PhuongTien", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.LoaiPhuongTien", "IdloaiPhuongTienNavigation")
//                         .WithMany("PhuongTiens")
//                         .HasForeignKey("IdloaiPhuongTien")
//                         .HasConstraintName("FK_PhuongTien_LoaiPhuongTien");

//                     b.HasOne("AspnetCoreMvcFull.Models.TrangThaiPhuongTien", "IdtrangThaiNavigation")
//                         .WithMany("PhuongTiens")
//                         .HasForeignKey("IdtrangThai")
//                         .HasConstraintName("FK_PhuongTien_TrangThaiPhuongTien");

//                     b.Navigation("IdloaiPhuongTienNavigation");

//                     b.Navigation("IdtrangThaiNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TraiCay", b =>
//                 {
//                     b.HasOne("AspnetCoreMvcFull.Models.LoaiTraiCay", "IdloaiTraiCayNavigation")
//                         .WithMany("TraiCays")
//                         .HasForeignKey("IdloaiTraiCay")
//                         .HasConstraintName("FK_TraiCay_LoaiTraiCay");

//                     b.Navigation("IdloaiTraiCayNavigation");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.BoPhan", b =>
//                 {
//                     b.Navigation("NhanViens");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.DoanhNghiep", b =>
//                 {
//                     b.Navigation("DoanhNghiepPhuongTiens");

//                     b.Navigation("HopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.HopDong", b =>
//                 {
//                     b.Navigation("ChiTietHopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.Kho", b =>
//                 {
//                     b.Navigation("ChiTietKhos");

//                     b.Navigation("KhoPhuongTiens");

//                     b.Navigation("LoHangs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoHang", b =>
//                 {
//                     b.Navigation("ChiTietHopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiHopDong", b =>
//                 {
//                     b.Navigation("HopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiLoHang", b =>
//                 {
//                     b.Navigation("LoHangs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiPhuongTien", b =>
//                 {
//                     b.Navigation("PhuongTiens");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.LoaiTraiCay", b =>
//                 {
//                     b.Navigation("TraiCays");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.NhaCungCap", b =>
//                 {
//                     b.Navigation("HopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.NhanVien", b =>
//                 {
//                     b.Navigation("HopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.PhuongTien", b =>
//                 {
//                     b.Navigation("ChiTietHopDongs");

//                     b.Navigation("DoanhNghiepPhuongTiens");

//                     b.Navigation("KhoPhuongTiens");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.QuocGium", b =>
//                 {
//                     b.Navigation("DoanhNghieps");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TraiCay", b =>
//                 {
//                     b.Navigation("ChiTietKhos");

//                     b.Navigation("GiaTraiCays");

//                     b.Navigation("LoHangs");

//                     b.Navigation("NhaCungCaps");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiHopDong", b =>
//                 {
//                     b.Navigation("ChiTietHopDongs");

//                     b.Navigation("HopDongs");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiNhanVien", b =>
//                 {
//                     b.Navigation("NhanViens");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiPhuongTien", b =>
//                 {
//                     b.Navigation("PhuongTiens");
//                 });

//             modelBuilder.Entity("AspnetCoreMvcFull.Models.TrangThaiVanChuyen", b =>
//                 {
//                     b.Navigation("DoanhNghiepPhuongTiens");

//                     b.Navigation("KhoPhuongTiens");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
